---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Vault encrypt a given file
      vars:
        vault_pass: v3rys3cur3
      expect:
        command: ansible-vault encrypt --ask-vault-pass EncryptedText.txt
        responses:
          New Vault password: "{{ vault_pass }}"
          Confirm New Vault password: "{{ vault_pass }}"
